CREATE TABLE public.db_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255),
    login VARCHAR(255) UNIQUE,
    "name" VARCHAR(150) NOT NULL,
    "password" VARCHAR(255)
);

CREATE TABLE public.db_book (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    book_cod INT NOT NULL UNIQUE,
    amount INT NOT NULL
);

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'reserve_status') THEN
        CREATE TYPE reserve_status AS ENUM ('APPROVED', 'REJECTED');
    END IF;
END $$;


CREATE TABLE public.tb_reserve (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    name_book VARCHAR(255) NOT NULL,
    reserve_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status reserve_status NOT NULL
);

CREATE TABLE public.db_author (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    nationality VARCHAR(255),
    biography TEXT,
    email VARCHAR(255) UNIQUE
);


CREATE TABLE public.db_publisher (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    city VARCHAR(255),
    country VARCHAR(255),
    email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE public.db_isbn (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number VARCHAR(255) NOT NULL UNIQUE,
    edition VARCHAR(255),
    year_publication INT,
    publisher_id BIGINT,
    CONSTRAINT fk_isbn_publisher FOREIGN KEY (publisher_id) REFERENCES db_publisher(id) ON DELETE SET NULL
);
